#pragma once

// Trackbar Textures
#define IDB_TRACKBAR_BG         "NXA_TRACKBAR_BG"
#define IDB_TRACKBAR_ATLAS_BG   "NXA_TRACKBAR_ATLAS_BG"
#define IDB_TRACKBAR_NUB        "NXA_TRACKBAR_NUB"

// Checkbox Textures
#define IDB_CHECKBOX_UNCHECKED          "NXA_CB_UNCHECKED"
#define IDB_CHECKBOX_UNCHECKED_ACTIVE   "NXA_CB_UNCHECKED_ACTIVE"
#define IDB_CHECKBOX_UNCHECKED_DISABLED "NXA_CB_UNCHECKED_DISABLED"
#define IDB_CHECKBOX_CHECKED            "NXA_CB_CHECKED"
#define IDB_CHECKBOX_CHECKED_ACTIVE     "NXA_CB_CHECKED_ACTIVE"
#define IDB_CHECKBOX_CHECKED_DISABLED   "NXA_CB_CHECKED_DISABLED"

// Audio
#define IDR_AUDIO_CLICK         "NXA_AUDIO_CLICK"

// Dropdown
#define IDB_DROPDOWN_ARROW      "NXA_DD_ARROW"

// Button
#define IDB_BUTTON_STATES       "NXA_BUTTON_STATES"
#define IDB_BUTTON_BORDER       "NXA_BUTTON_BORDER"

// Menu
#define IDR_WAV_MENUCLICK1      "NXA_WAV_MENUCLICK1"
#define IDR_WAV_MENUCLICK2      "NXA_WAV_MENUCLICK2"
#define IDR_WAV_MENUCLICK3      "NXA_WAV_MENUCLICK3"
#define IDR_WAV_MENUCLICK4      "NXA_WAV_MENUCLICK4"

// Fonts
#define IDR_FONT_MENOMONIA      "NXA_FONT_MENOMONIA"
