#pragma once

#define IDB_TRACKBAR_BG             "NXA_TRACKBAR_BG"
#define IDB_TRACKBAR_ATLAS_BG       "NXA_TRACKBAR_ATLAS_BG"
#define IDB_TRACKBAR_NUB            "NXA_TRACKBAR_NUB"

#define IDB_CHECKBOX_UNCHECKED          "NXA_CB_UNCHECKED"
#define IDB_CHECKBOX_UNCHECKED_ACTIVE   "NXA_CB_UNCHECKED_ACTIVE"
#define IDB_CHECKBOX_UNCHECKED_DISABLED "NXA_CB_UNCHECKED_DISABLED"
#define IDB_CHECKBOX_CHECKED            "NXA_CB_CHECKED"
#define IDB_CHECKBOX_CHECKED_ACTIVE     "NXA_CB_CHECKED_ACTIVE"
#define IDB_CHECKBOX_CHECKED_DISABLED   "NXA_CB_CHECKED_DISABLED"

#define IDR_AUDIO_BUTTON_CLICK  "NXA_AUDIO_BUTTON_CLICK"

#define IDB_DROPDOWN_ARROW "NXA_DD_ARROW"

#define IDB_BUTTON_STATES "NXA_BUTTON_STATES"
#define IDB_BUTTON_BORDER "NXA_BUTTON_BORDER"

#define IDB_DIALOG_ICONS "NXA_DIALOG_ICONS"
#define IDB_DIALOG_BG "NXA_DIALOG_BG"
#define IDR_AUDIO_MENU_ITEM_CLICK "NXA_AUDIO_MENU_ITEM_CLICK"
